plugins {
    id 'java'
}

group = 'com.payaza'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'software.amazon.awssdk:aws-sdk-java:2.31.18'
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
    implementation 'com.amazonaws:aws-lambda-java-events:3.15.0'
    implementation 'com.amazonaws:aws-lambda-java-tests:1.1.1'
    implementation 'com.amazonaws:aws-lambda-java-events-sdk-transformer:3.1.0'
    implementation 'com.amazonaws:aws-lambda-java-runtime-interface-client:2.6.0'
    implementation 'com.amazonaws:aws-lambda-java-serialization:1.1.5'

    implementation 'org.mongodb:mongo-java-driver:3.12.14'
    implementation 'org.mindrot:jbcrypt:0.4'

    implementation 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.38'

    implementation 'org.mockito:mockito-junit-jupiter:5.17.0'

    testImplementation 'org.projectlombok:lombok:1.18.38'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.38'

    testImplementation 'uk.org.webcompere:system-stubs-core:2.1.8'
    testImplementation 'uk.org.webcompere:system-stubs-testng:2.1.8'
    testImplementation 'uk.org.webcompere:system-stubs-jupiter:2.1.8'
}

test {
    useJUnitPlatform()
}